services:
  app:
    build: .
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: 'development'
    entrypoint: make dev
    ports:
      - 8080:8080

  caddy:
    image: caddy:2.6
    restart: unless-stopped
    depends_on: [app]
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
