services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    command: ["make", "dev"]
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.6
    restart: unless-stopped
    depends_on: [app]
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: