FROM node:20.12.2
WORKDIR /app

# Важно для кеширования слоев
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm install

COPY app/. .

EXPOSE 8080

CMD make start
